os: linux
dist: trusty
sudo: required
language: cpp
compiler: gcc

env:
  matrix:
    - BUILD=linux
    - BUILD=linux-cuda
    - BUILD=linux-cuda-cudnn

matrix:
  include:
    - os: osx
      compiler: clang
      env: BUILD=osx

before_install:
  - source scripts/travis/setup.sh

install:
  - ./scripts/travis/install.sh
  - ./scripts/travis/build.sh

script:
  - echo $TRAVIS_BUILD_DIR

cache:
  apt: true
